BiGRU:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

BiLSTM:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

CNN1D:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

UNET_NILM:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: 0
    training_in_model: false

FCN:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

DResNet:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

DAResNet:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

BERT4NILM:
  model_kwargs:
    cutoff: 10000
    threshold: 0
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

DiffNILM:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-3
    wd: !!float 0
    training_in_model: true

STNILM:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-3
    wd: !!float 0
    training_in_model: true

TSILNet:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

Energformer:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

NILMFormer:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-4
    wd: !!float 0
    training_in_model: false

ConvNet:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-3
    wd: !!float 0

ResNet:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-3
    wd: !!float 0

Inception:
  model_kwargs: {}
  model_training_param:
    lr: !!float 1e-3
    wd: !!float 0